# Gruvbox Baby for Helix with Tree-sitter scopes and palette reuse
# Based on the gruvbox-baby theme (see e.g. https://github.com/luisiacc/gruvbox-baby/blob/main/lua/gruvbox-baby/theme.lua) :contentReference[oaicite:1]{index=1}

# --------------------------------------------------
# Diagnostic Groups
# --------------------------------------------------
error   = { fg = "red", modifiers = ["bold"] }
warning = { fg = "bright_yellow" }
info    = { fg = "light_blue" }
hint    = { fg = "forest_green" }       # palette.forest_green = "#689d6a"

"diagnostic" = { underline = { color = "orange", style = "curl" } }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.hint" = { underline = { color = "clean_blue", style = "curl" } }
"diagnostic.info" = { underline = { color = "forest_green", style = "curl" } }
"diagnostic.warning" = { underline = { color = "bright_yellow", style = "curl" } }

"diff.delta" = { fg = "bright_yellow" }
"diff.minus" = { fg = "red" }
"diff.plus" = { fg = "clean_green" }

# --------------------------------------------------
# UI Elements
# --------------------------------------------------
"ui.background"         = { bg = "background" }
"ui.text"               = "foreground"
# "ui.linenr"             = { fg = "medium_gray" }    # palette.medium_gray = "#504945"
# "ui.statusline"         = { fg = "foreground", bg = "dark" }  # palette.dark = "#202020"
# "ui.gutter"             = { fg = "comment" }
# "ui.cursorline.primary" = { bg = "background_light" }

"ui.selection" = { bg = "background_light" }
"ui.selection.primary" = { bg = "bg2" }

"ui.cursor"                = { fg = "bg1", bg = "fg4" }
"ui.cursor.insert"         = { fg = "bg1", bg = "light_blue" }
"ui.cursor.normal"         = { fg = "bg1", bg = "fg4" }
"ui.cursor.select"         = { fg = "bg1", bg = "orange" }
"ui.cursor.match"          = { fg = "fg3", bg = "bg3" }

"ui.cursor.primary"        = { fg = "bg1", bg = "fg3" }
"ui.cursor.primary.insert" = { fg = "bg1", bg = "light_blue" }
"ui.cursor.primary.normal" = { fg = "bg1", bg = "fg3" }
"ui.cursor.primary.select" = { fg = "bg1", bg = "orange" }

"ui.cursorline" = { bg = "bg0_s" }
"ui.cursorline.primary" = { bg = "bg1" }

"ui.window" = { bg = "bg1" }
"ui.menu" = { fg = "fg1", bg = "bg1" }
"ui.menu.selected" = { fg = "bg2", bg = "light_blue", modifiers = ["bold"] }
"ui.popup" = { bg = "bg1" }
"ui.picker.header.column" = { underline.style = "line" }
"ui.picker.header.column.active" = { modifiers = ["bold"], underline.style = "line" }

"special" = { fg = "red" }

"ui.text.directory" = { fg = "light_blue" }
"ui.virtual.inlay-hint" = { fg = "gray" }
"ui.virtual.jump-label" = { fg = "magenta", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.whitespace" = "bg2"
"ui.virtual.wrap" = { fg = "bg2" }

# --------------------------------------------------
# Tree-sitter Scopes
# (These keys match the Tree-sitter scopes documented in Helix) :contentReference[oaicite:2]{index=2}
# --------------------------------------------------
"constant.builtin"               = { fg = "orange" }
"comment"               = { fg = "comment", modifiers = ["italic"] }
"constant"              = { fg = "pink", modifiers = ["bold"] }
"string"                = { fg = "soft_green" }
"character"             = { fg = "soft_green" }
"number"                = { fg = "bright_yellow" }
"function"              = { fg = "soft_yellow", modifiers = ["bold"] }
"function.macro"        = { fg = "orange" }
"function.call"         = { fg = "soft_yellow", modifiers = ["bold"] }
"keyword"               = { fg = "red", modifiers = ["bold"] }
"operator"              = { fg = "foreground" }
"variable"              = { fg = "light_blue" }
"variable.other.member" = { fg = "blue_gray" }
"type"                  = { fg = "clean_green" }
"type.builtin"          = { fg = "blue_gray" }       # palette.blue_gray = "#458588"
"attribute"             = { fg = "bright_yellow" }
"namespace"             = { fg = "clean_green" }
"punctuation.delimiter" = { fg = "foreground" }
"punctuation.bracket"   = { fg = "foreground" }
"punctuation.special"   = { fg = "foreground" }
"text"                  = { fg = "foreground" }
"text.strong"           = { fg = "foreground", modifiers = ["bold"] }
"text.emphasis"         = { fg = "foreground", modifiers = ["italic"] }
"text.underline"        = { fg = "foreground", modifiers = ["underline"] }
"text.strike"           = { fg = "medium_gray", modifiers = ["strikethrough"] }
"tag"                   = { fg = "clean_green"} 
"constructor"           = { fg = "clean_green"} 

# --------------------------------------------------
# Palette (for internal reference and reuse)
# --------------------------------------------------
[palette]
bg0_s = "#32302f"
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#47403b"

fg0 = "#fbf1c7"
fg1 = "#ebdbb2" # main foreground
fg2 = "#d5c4a1"
fg3 = "#bdae93"
fg4 = "#766B54"

dark              = "#202020"
foreground        = "#ebdbb2"
background        = "#282828"
background_dark   = "#1d2021"
background_light  = "#32302f"
medium_gray       = "#504945"
comment           = "#665c54"
gray              = "#DEDEDE"
soft_yellow       = "#eebd35"
soft_green        = "#98971a"
bright_yellow     = "#fabd2f"
orange            = "#d65d0e"
red               = "#fb4934"
error_red         = "#cc241d"
magenta           = "#b16286"
pink              = "#D4879C"
light_blue        = "#7fa2ac"
dark_gray         = "#83a598"
blue_gray         = "#458588"
forest_green      = "#689d6a"
clean_green       = "#8ec07c"
milk              = "#E7D7AD"

