-- require('user.settings')
-- require('user.keys')
-- require('user.plugins')
-- require('user.colors')
-- require('user.treesitter')
-- require('user.lsp')
-- require('user.telescope')
-- require('user.tree')
-- require('user.cmp')

-- Setup lazy.nvim
require("config.lazy")
require("config.globals")
require("config.mappings")
require("config.plugins")
require("config.diagnostic")
